id = "open-project"
name = "Open Project"
bundle_id = "com.graysurf.open-project"
version = "1.1.6"
script_filter = "script_filter.sh"
action = "action_open.sh"
rust_binary = "workflow-cli"
assets = [
  "src/assets/icon.png",
  "src/assets/icon-github.png",
  "src/8F3399E3-951A-4DC0-BC7D-CFA83C1E1F76.png",
]

[env]
PROJECT_DIRS = "$HOME/Project,$HOME/.config"
USAGE_FILE = "$HOME/.config/zsh/cache/.alfred_project_usage.log"
VSCODE_PATH = "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
OPEN_PROJECT_MAX_RESULTS = "30"

[alfred]
min_alfred = "5"
min_macos = "13.0"
