[package]
name = "workflow-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
workflow-common = { path = "../workflow-common" }

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
