[package]
name = "nils-alfred-plist"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "alfred_plist"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
