[package]
name = "workflow-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alfred-core = { path = "../alfred-core" }
chrono.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
