id = "__WORKFLOW_ID__"
name = "__WORKFLOW_NAME__"
bundle_id = "com.graysurf.__WORKFLOW_ID__"
version = "0.1.0"
script_filter = "script_filter.sh"
action = "action_open.sh"
rust_binary = "workflow-cli"
assets = ["src/assets/icon.png"]

[env]
EXAMPLE_VAR = "example"

[alfred]
min_alfred = "5"
min_macos = "13.0"
